package com.a5670;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;

import com.a1234.Connection;

public class Website7 
{
	public static void main(String[] args) throws InterruptedException 
	{
		WebDriver driver = Connection.getconnection("https://only-testing-blog.blogspot.com/");
		
		
		JavascriptExecutor js = (JavascriptExecutor) driver;
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,document.body.scrollHeight)");
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[1]/div/div/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("gparent_1")).sendKeys("manishbhai");
		Thread.sleep(1000);
		driver.findElement(By.id("parent_1")).sendKeys("pareshbhi");
		Thread.sleep(1000);
		driver.findElement(By.id("child_1")).sendKeys("riddhi");
		Thread.sleep(1000);
		driver.findElement(By.id("gparent_2")).sendKeys("abc");
		Thread.sleep(1000);
		driver.findElement(By.id("parent_2")).sendKeys("xyz");
		Thread.sleep(1000);
		driver.findElement(By.id("child_2")).sendKeys("gkm");
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[2]/div/div/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("tooltip-1")).sendKeys("urvi");
		Thread.sleep(1000);
		driver.findElement(By.id("sname")).sendKeys("mandani");
		Thread.sleep(1000);
		driver.findElement(By.id("yaddress")).sendKeys("rajkot");
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[3]/div/div/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("text1")).sendKeys("Delhi");
		Thread.sleep(1000);
		driver.findElement(By.id("text2")).sendKeys("India");
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[4]/div/div/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-3107268830657760720\"]/div[1]/table/tbody/tr[2]/td[2]/input")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,document.body.scrollHeight)");
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[5]/div/div/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"selectable\"]/li[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("datepicker")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("15")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[6]/div/div/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[7]/div/div/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.name("fname")).sendKeys("abc");
		Thread.sleep(1000);
		driver.findElement(By.name("lname")).sendKeys("xyz");
		Thread.sleep(1000);
		driver.findElement(By.name("sname")).sendKeys("opl");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-536524247070242612\"]/div[1]/table/tbody/tr[4]/td[1]/input")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[8]/div/div/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.name("fname")).sendKeys("fgy");
		Thread.sleep(1000);
		driver.findElement(By.name("lname")).sendKeys("jtl");
		Thread.sleep(1000);
		driver.findElement(By.id("submitButton")).click();
		Alert alert =   driver.switchTo().alert();
		alert.accept();
		driver.findElement(By.linkText("Home")).click();
		js.executeScript("window.scrollTo(0,document.body.scrollHeight)");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[9]/div/div/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.name("FirstName")).sendKeys("abc");
		Thread.sleep(1000);
		driver.findElement(By.name("LastName")).sendKeys("xyz");
		Thread.sleep(1000);
		driver.findElement(By.name("EmailID")).sendKeys("abc@gmail.com");
		Thread.sleep(1000);
		driver.findElement(By.name("MobNo")).sendKeys("4388807655");
		Thread.sleep(1000);
		driver.findElement(By.name("Company")).sendKeys("fyb company");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-8228718889842861683\"]/div[1]/form/input[6]")).click();
		alert.accept();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[10]/div/div/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.name("userid")).sendKeys("urvi");
		Thread.sleep(1000);
		driver.findElement(By.name("pswrd")).sendKeys("3456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-4024384759750876807\"]/div[1]/form/input[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.name("fname")).sendKeys("dgy");
		Thread.sleep(1000);
		driver.findElement(By.name("lname")).sendKeys("juy");
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		js.executeScript("window.scrollTo(0,document.body.scrollHeight)");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"Blog1\"]/div[1]/div[11]/div/div[1]/div/h3/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-3409116931169700903\"]/form/table/tbody/tr[2]/td/input[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-3409116931169700903\"]/form/table/tbody/tr[2]/td/input[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-3409116931169700903\"]/form/table/tbody/tr[2]/td/input[7]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-3409116931169700903\"]/form/table/tbody/tr[2]/td/input[13]")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Sub")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-4475596368583819756\"]/form/table/tbody/tr[2]/td/input[5]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-4475596368583819756\"]/form/table/tbody/tr[2]/td/input[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-4475596368583819756\"]/form/table/tbody/tr[2]/td/input[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-4475596368583819756\"]/form/table/tbody/tr[2]/td/input[13]")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Add")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-3123406043331795498\"]/form/table/tbody/tr[2]/td/input[10]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-3123406043331795498\"]/form/table/tbody/tr[2]/td/input[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-3123406043331795498\"]/form/table/tbody/tr[2]/td/input[8]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"post-body-3123406043331795498\"]/form/table/tbody/tr[2]/td/input[13]")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Calc")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("8")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("divide")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("2")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("equals")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		js.executeScript("window.scrollTo(0,document.body.scrollHeight)");
		Thread.sleep(1000);
		driver.findElement(By.linkText("Attributes")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("text1")).sendKeys("yui");
		driver.findElement(By.id("option2")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("radio2")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("TextBox")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("text1")).sendKeys("yui");
		driver.findElement(By.id("check2")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("radio2")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("Carlist")).click();
		driver.findElement(By.id("car3")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("France")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Show Me Confirmation")).click();
		alert.accept();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Show Me Prompt")).click();
		alert.accept();
		driver.findElement(By.id("submitButton")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("New Testing")).click();
		Thread.sleep(1000);
		driver.findElement(By.name("fname")).sendKeys("vbn");
		Thread.sleep(1000);
		driver.findElement(By.name("vehicle")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Female")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Saab")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("India")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Show Me Confirmation")).click();
		alert.accept();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Show Me Prompt")).click();
		alert.accept();
		driver.findElement(By.id("submitButton")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("New Test")).click();
		Thread.sleep(1000);
		driver.findElement(By.name("fname")).sendKeys("kyr");
		Thread.sleep(1000);
		driver.findElement(By.name("vehicle")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Female")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Saab")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("India")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Show Me Confirmation")).click();
		alert.accept();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Show Me Prompt")).click();
		alert.accept();
		driver.findElement(By.id("submitButton")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		js.executeScript("window.scrollTo(0,document.body.scrollHeight)");
		Thread.sleep(1000);
		driver.findElement(By.linkText("Table")).click();
		Thread.sleep(1000);
		driver.findElement(By.name("fname")).sendKeys("kyr");
		Thread.sleep(1000);
		driver.findElement(By.name("vehicle")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Female")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Saab")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("India")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Get Confirmation")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("submitButton")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Testing")).click();
		Thread.sleep(1000);
		driver.findElement(By.name("fname")).sendKeys("kyr");
		Thread.sleep(1000);
		driver.findElement(By.name("vehicle")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Female")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Saab")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("India")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("submitButton")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Home")).click();
		Thread.sleep(1000);
		
	
	}

}
