package com.a5670;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;

public class Website5 
{
	public static void main(String[] args) throws InterruptedException 
	{
		System.setProperty("webdriver.chrome.driver","D:\\newdata\\chromedriver-win64\\chromedriver.exe");	
		WebDriver driver = new ChromeDriver();
		driver
		.get("https://jqueryui.com/");
		driver.manage().window().maximize();
	
		driver.findElement(By.linkText("jQuery UI")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Demos")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Download")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("version-1.12.1")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Toggle All")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("position")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("widgets/resizable")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("effects/effect-bounce")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("theme")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Smoothness")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("scope")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"download-builder\"]/form/input")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("API Documentation")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Themes")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-2")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-3")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-1")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ffDefault")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("fwDefault")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("A button element")).click();
		Thread.sleep(1000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,200)");
		driver.findElement(By.linkText("Choice 1")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Standard")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-12")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,200)");
		driver.findElement(By.id("dialog-link")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Ok")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"icons\"]/li[53]/span")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,200)");
		driver.findElement(By.linkText("15")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Medium")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Slow")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("spinner")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-15")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,200)");
		driver.findElement(By.linkText("Development")).click();
		Thread.sleep(1000);
	    driver.findElement(By.linkText("Blog")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("2")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("3")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("4")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("5")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("6")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("7")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("8")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("9")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("10")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("About")).click();
		Thread.sleep(1000);
		
		driver.findElement(By.linkText("Draggable")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Constrain movement")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(driver.findElement(By.xpath("//*[@id=\"draggable\"]")));
		WebElement from = driver.findElement(By.xpath("//*[@id=\\\"draggable\\\"]"));
		WebElement to = driver.findElement(By.xpath("//*[@id=\"draggable2\"]"));
		Actions builder = new Actions(driver);
		Action dd = builder.clickAndHold(from).moveToElement(to).release().build();
		dd.perform();
		Thread.sleep(5000);
		
		driver.findElement(By.linkText("Droppable")).click();
		Thread.sleep(1000);
        driver.switchTo().frame(driver.findElement(By.xpath("//*[@id=\"content\"]/div[1]/ul/li[2]/a")));
		WebElement from1 = driver.findElement(By.xpath("//*[@id=\"draggable-nonvalid\"]"));
		WebElement to1 = driver.findElement(By.xpath("//*[@id=\"droppable\"]"));
		Actions builder1 = new Actions(driver);
		Action dd1 = builder.clickAndHold(from).moveToElement(to).release().build();
		dd.perform();
		Thread.sleep(5000);
		
		driver.findElement(By.linkText("Resizable")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"content\"]/div[1]/ul/li[3]/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"resizable\"]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Selectable")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Display as grid")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"selectable\"]/li[5]")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Sortable")).click();
		Thread.sleep(1000);
		WebElement from2 = driver.findElement(By.xpath("//*[@id=\"sortable1\"]/li[2]"));
		WebElement to2 = driver.findElement(By.xpath("//*[@id=\"sortable2\"]/li[4]"));
		Actions builder2 = new Actions(driver);
		Action dd2 = builder.clickAndHold(from).moveToElement(to).release().build();
		dd.perform();
		Thread.sleep(5000);
		driver.findElement(By.linkText("Accordion")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-3")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-5")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-7")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.linkText("Autocomplete")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Custom data and display")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("project")).sendKeys("j");
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-11")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Button")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("A button element")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("An anchor")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Checkboxradio")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("radio-1")).click();
		driver.findElement(By.linkText("New York")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("checkbox-1")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("2 Star")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("checkbox-nested-1")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("2 Double")).click();
		driver.findElement(By.linkText("Controlgrou.p")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.linkText("Compact car")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-3")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/fieldset[1]/div/label[1]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Book Now!")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Datepicker")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"ui-datepicker-div\"]/div/a[1]/span")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("13")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Dialog")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.linkText("Animation")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("opener")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Close")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.linkText("Menu")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Categories")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-3")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Progressbar")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Indeterminate Value")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("colorButton")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Selectmenu")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Product Selection")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("150px")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-4")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Yellow")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-6")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.linkText("Slider")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.xpath("//*[@id=\"slider\"]/span")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Spinner")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/p[1]/span/a[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("getvalue")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Tabs")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-2")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("ui-id-3")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Tooltip")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Custom animation demo")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("show-option")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("hide-option")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("open-event")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.linkText("Add Class")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.id("button")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Color Animation")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.id("button")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Easing")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("1. linear")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("2. swing")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.linkText("Effect")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("effectTypes")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Bounce")).click();
		driver.findElement(By.id("button")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Hide")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("effectTypes")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Bounce")).click();
		driver.findElement(By.id("button")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Remove Class")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("button")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.linkText("Show")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("button")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Switch Class")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("button")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Toggle")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("effectTypes")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Clip")).click();
		driver.findElement(By.id("button")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.linkText("Toggle Class")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("button")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Position")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Image Cycler")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("next")).click();
		Thread.sleep(1000);
		driver.findElement(By.linkText("Widget Factory")).click();
		Thread.sleep(1000);
		js.executeScript("window.scrollTo(0,100)");
		driver.findElement(By.linkText("change")).click();
		driver.findElement(By.id("disable")).click();
		Thread.sleep(1000);
		driver.findElement(By.id("green")).click();
	
	
	}
	

}
