package com.a5670;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Website4 
{
	public static void main(String[] args) throws InterruptedException 
	{
	   	    System.setProperty("webdriver.chrome.driver","D:\\newdata\\chromedriver-win64\\chromedriver.exe");	
			WebDriver driver = new ChromeDriver();
			driver.get("https://www.saucedemo.com/");
			driver.manage().window().maximize();
		
			driver.findElement(By.id("user-name")).sendKeys("standard_user");
			Thread.sleep(1000);
			driver.findElement(By.id("password")).sendKeys("secret_sauce");
			Thread.sleep(1000);
			driver.findElement(By.id("login-button")).click();
			Thread.sleep(1000);
			driver.findElement(By.xpath("//*[@id=\"header_container\"]/div[2]/div/span/select/option[2]")).click();
			Thread.sleep(1000);
			driver.findElement(By.xpath("//*[@id=\"header_container\"]/div[2]/div/span/select/option[3]")).click();
			Thread.sleep(1000);
			driver.findElement(By.xpath("//*[@id=\"header_container\"]/div[2]/div/span/select/option[4]")).click();
			Thread.sleep(1000);
			driver.findElement(By.id("about_sidebar_link")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Platform for Test")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Sauce Cross-Browser")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Sauce Mobile")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Sauce Low-Code")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Sauce Error Reporting")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Sauce Orchestrate")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Sauce API Quality")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Sauce Visual")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Insights")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Performance")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Integrations & plugins")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Supported browsers & devices")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Products")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Platform configurator")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Enterprise")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Teams")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("CI/CD pipeline optimization")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Continuous testing")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Crash & error reporting")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Debugging")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Mobile application testing")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Mobile beta testing")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Scalable test automation")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Test analytics")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Test orchestration")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Visual testing")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("CI/CD")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Test automation")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Test management")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Test creation")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Accessibility")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Solutions")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("API management")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Pricing")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Documentation")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Changelog")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Support")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("FAQs")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Selenium")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Appium")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Cypress")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Playwright")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Mobile app testing")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Web app testing")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Test orchestration")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("CI")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Join our community")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Find an event")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Meet our experts")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Integrations")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Supported browsers & devices")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Platform configurator")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Developers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Test configuration")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Blog")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Webinars")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Videos")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Reports")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("White papers")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Demos")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Case studies")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("TEI Study")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Data sheets")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Security")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("All topics")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Automated testing")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Mobile testing")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Selenium")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Appium")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Playwright")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Cross-browser testing")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("Resources")).click();
			Thread.sleep(1000);
			driver.findElement(By.linkText("CI/CD")).click();
			Thread.sleep(1000);
			driver.findElement(By.id("add-to-cart-test.allthethings()-t-shirt-(red)")).click();
			Thread.sleep(1000);
			driver.findElement(By.id("react-burger-menu-btn")).click();
			Thread.sleep(1000);
			driver.findElement(By.id("inventory_sidebar_link")).click();
			Thread.sleep(1000);
			driver.findElement(By.id("reset_sidebar_link")).click();
			Thread.sleep(1000);
			driver.findElement(By.id("react-burger-cross-btn")).click();
	        Thread.sleep(1000);
	        driver.findElement(By.id("logout_sidebar_link")).click();
			
	}

}
